# Generated by Django 5.2.5 on 2025-09-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categoria_id',
            new_name='categoria',
        ),
    ]
